### ISSUE TITLE
EXTRA_LAUNCH_ARGS are not honored

### ISSUE THREAD

**Issue by jrsperry** [Atinoda/text-generation-webui-docker#25]
Running in kubernetes, it works fine except the EXTRA_LAUNCH_ARGS are not honored as env vars. 

The following I would expect to enable the api and preload a model, neither are enabled though. 
```
            - name: EXTRA_LAUNCH_ARGS
              value: "--listen --verbose --api --extensions api --model TheBloke/vicuna-13B-v1.5-GPTQ --gpus all"
```

 full kubernetes deployment: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-gen-webui
  namespace: text-gen-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: text-gen-webui
  template:
    metadata:
      labels:
        component: text-gen-webui
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          value: present
          effect: NoSchedule
      containers:
        - name: text-gen-demo-container
          image: atinoda/text-generation-webui
          ports:
            - containerPort: 7860
            - containerPort: 5000
            - containerPort: 5005
          resources:
            limits:
              nvidia.com/gpu: "1"
          env:
            - name: EXTRA_LAUNCH_ARGS
              value: "--listen --verbose --api --extensions api --model TheBloke/vicuna-13B-v1.5-GPTQ --gpus all"
            - name: TORCH_CUDA_ARCH_LIST
              value: "7.5"
          volumeMounts:
            - name: text-gen-demo-pvc
              mountPath: /app/loras
              subPath: loras
            - name: text-gen-demo-pvc
              mountPath: /app/models
              subPath: models
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: text-gen-demo-pvc
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
```

**Comment by accountForIssues** [comment]
I use Kubernetes as well and spent a long time trying to figure this out.

In the end, though, it appears that only the first argument is honored i.e., anything after the first whitespace character is being ignored.

If I escape the whitespace however, it seems to work.

This is the only app I have noticed that didn't work with quotes and required escaping spaces.

(part of) my deployment:
```yaml
          env:
          - name:  EXTRA_LAUNCH_ARGS
            value: --listen\ --verbose
```
