### ISSUE TITLE
how to configure for CPU only?

### ISSUE THREAD

**Issue by jatinsne** [Atinoda/text-generation-webui-docker#9]

**Comment by Atinoda** [comment]
Comment out the GPU part of the `docker-compose.yml`. If you have no GPU, then of course you also do not need to install the cuda docker runtime! So your `docker-compose.yml` could look like this:

```
version: "3"
services:
  text-generation-webui-docker:
    image: atinoda/text-generation-webui:default # Specify variant as the :tag
    container_name: text-generation-webui
    environment:
      - EXTRA_LAUNCH_ARGS="--listen --verbose" # Custom launch args (e.g., --model MODEL_NAME)
#      - BUILD_EXTENSIONS_LIVE="silero_tts whisper_stt" # Install named extensions during every container launch. THIS WILL SIGNIFICANLTLY SLOW LAUNCH TIME.
    ports:
      - 7860:7860  # Default web port
#      - 5000:5000  # Default API port
#      - 5005:5005  # Default streaming port
#      - 5001:5001  # Default OpenAI API extension port
    volumes:
      - ./config/loras:/app/loras
      - ./config/models:/app/models
      - ./config/presets:/app/presets
      - ./config/prompts:/app/prompts
      - ./config/softprompts:/app/softprompts
      - ./config/training:/app/training
#      - ./config/extensions:/app/extensions
    logging:
      driver:  json-file
      options:
        max-file: "3"   # number of files or file count
        max-size: '10m'
#    deploy:
#        resources:
#          reservations:
#            devices:
#              - driver: nvidia
#                device_ids: ['0']
#                capabilities: [gpu]
```
*Note the '#' before all the ending lines, starting from `deploy:` which disables the GPU support.*
